---
- hosts: all
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install packages
      apt:
        pkg:
          - vim
          - vim-nox
          - git
          - curl
          - wget
          - htop
        state: latest
        update_cache: true