---
- hosts: all
  become: true
  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - curl
        state: latest
        update_cache: true

    - name: Add GitLab GPG apt key
      apt_key:
        url: https://packages.gitlab.com/gpg.key
        state: present

    - name: Download GitLab installer
      get_url: 
        url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh 
        dest: /tmp/gitlab-runner-script.deb.sh
        mode: 755
    
    - name: Execute GitLab installer
      shell: /tmp/gitlab-runner-script.deb.sh

    - name: Remove GitLab installer
      file:
        path: /tmp/gitlab-runner-script.deb.sh
        state: absent

    - name: Install GitLab Runner
      apt:
        name: gitlab-runner
        state: latest
        update_cache: true
